views:
  - name: avg_salary_by_department
    description: This metric tracks the percentage of leads or prospects who successfully converted into paying employees over a month time period. It provides insights into the effectiveness of marketing efforts and sales processes.
    public: true
    meta:
      title: Average Salary by Department 
      tags: 
        - DPDomain.HRAnalysis 
        - DPUsecase.Employee Analysis
        - DPTier.Business Certified
      metric:
        expression: "*/5  * * * *"
        timezone: "UTC"
        window: "month" 

    tables:
      - join_path: employee
        prefix: true
        includes:
          - avg_salary
          - department