version: "2.2"

x-lens2-environment: &lens2-environment
  # DataOS
  DATAOS_FQDN: proud-cobra.dataos.app  
  # Overview
  LENS2_NAME: employee
  LENS2_DESCRIPTION: "Retail"
  LENS2_TAGS: "employee insights"
  LENS2_AUTHORS: aayushisolanki
  LENS2_SOURCE_TYPE: depot
  LENS2_SOURCE_NAME: snowflake  #cluster_name
  # LENS2_SOURCE_CATALOG_NAME:  #icebase
  DATAOS_RUN_AS_APIKEY: dG9rZW5fcmVtYXJrYWJseV9zbG93bHlfYXdhcmVfa2FuZ2Fyb28uNGMxYmQ1ODItM2Q4Ni00MWEyLTkwZmEtNmZhMWJjNGEwMWNk
    # Log
  LENS2_LOG_LEVEL: error
  CACHE_LOG_LEVEL: error
  # Operation
  
  LENS2_DEV_MODE: "true"  
  LENS2_REFRESH_WORKER: "true"
  LENS2_SCHEMA_PATH: model
  LENS2_PG_SQL_PORT: 5432

services:
  api:
    restart: always
    image: rubiklabs/lens2:0.35.60-8 #.41-05 or .18-50  0.35.
    ports:
      - 4000:4000
      - 25432:5432
      - 13306:13306
    environment:
      <<: *lens2-environment   
    volumes:
      - ./model:/etc/dataos/work/model