name: insurance-lens-02
version: v1alpha
type: lens
tags:
  - lens
description: Data model for insurance intelligence
owner: aayushisolanki
workspace: curriculum
lens:
  compute: runnable-default
  secrets:
    - name: githubr
      allKeys: true
  source:
    type: depot
    name: snowflake  #name of the depot
    # catalog: icebase
  repo:
    url: https://github.com/Aayushitmdc/lens_policy_testing
    lensBaseDir: lens_policy_testing/insurance/model
    syncFlags:
      - '--ref=main'
  api:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 2048Mi
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES: "UTC,America/Vancouver,America/Toronto"
  router:
    logLevel: info
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 3048Mi
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES:  "UTC,America/Vancouver,America/Toronto"
  worker:
    logLevel: debug
    replicas: 2
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 2000m
        memory: 3048Mi
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES:  "UTC,America/Vancouver,America/Toronto"
  iris:
    logLevel: info
    replicas: 1
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 4600m
        memory: 8240Mi
    envs:
      LENS2_SCHEDULED_REFRESH_TIMEZONES:  "UTC,America/Vancouver,America/Toronto"
